name: Paper PDF
run-name: Build paper PDF from LaTeX source
on: [push]
jobs:
  Build-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Compile PDF with Makefile in `paper-tex` directory
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            cd ./paper-tex
            make all
      - name: Copy generated paper PDF to repository root
        run: cp ./paper-tex/08-Security-Software.pdf .
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: "./08-Security-Software.pdf"
          default_author: github_actions
          message: Add paper PDF built with GitHub Actions